name: 🧾 Latest blog post workflow
on:
  schedule:
    # Schedule to run the workflow daily at midnight
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://techdufus.com/feed.xml"
          max_post_count: 15
