name: 💰 Update Sponsors
on:
  push:
    paths: 
      - ".github/SPONSORS.yml"

jobs:
  update-sponsors-section:
    name: Update this repo's README's sponsors.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: matthewjdegarmo/Sponsors@main
        with:
          sponsors_file: ./.github/SPONSORS.yml
          readme_file: ./README.md
